### ISSUE TITLE
Getting ramped up

### ISSUE THREAD

**Issue by ckcollab** [ckcollab/friendcation-automaton#1]
# TODO
### Install
- [x] [PyCharm](https://www.jetbrains.com/pycharm-edu/) (our IDE) 
- [x] [Python](https://www.python.org/ftp/python/3.5.2/python-3.5.2.exe) 
- [x] Setup PATH environment variable, so the command line knows where `python` lives
  - [x] In Win10 I was able to pull up the Environment Variable manager by just typing "PATH" into the Ask Me Anything start menu thing
  - [x] Add `C:\Users\Eric\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\Eric\AppData\Local\Programs\Python\Python35-32\;` to your path replacing `Eric` with your account name and make sure the directory exists
- [x] Install `pip` by running `python -m pip install -U pip` in terminal
- [x] `pip install pyautoit`
### Optional extras

These give us better copy and paste, nice linux commands in windows (like `ls` instead of `dir`)
- [ ] [Git](https://git-scm.com/download/win) Choose the option to include Unix command line tools
- [ ] [ConEmu](http://www.fosshub.com/ConEmu.html/ConEmuSetup.160619.exe) (a better Terminal/command prompt to work in)
  - [ ] Set `preferred color scheme` to `Monokai`
# Test it out

Run `python` in your terminal which will drop you into a REPL (Read Eval Print Loop, as in, read in some text, run it, print the result, do it all over again)

``` bash
> python
```

You should see something like this as output:

``` bash
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Now let's try to use `pyautoit`!

``` bash
>>> import autoit
>>> # Let's open a notepad window just to check that this all works
>>> autoit.run("notepad.exe")
4396
>>> exit()
```
